# server
#server.port=8889
#spring.application.name=personal_blog
server:
  port: 8889
spring:
  profiles:
    active: dev
  application:
    name: blog-server #ָ服务名

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


myth:
  es:
    hostlist: 127.0.0.1:9200 #多个节点用逗号隔开

aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: LTAI5tSAEumpRXh4NUEPLDbU
      keysecret: oDG6bMThg2oy9Ibbk0kiOjPPszdYeo
      bucketname: blog-myth