eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  redis:
    host: 127.0.0.1

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000