server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: blog-gateway

zuul:
  host:
    connect-timeout-millis: 60000000
    socket-timeout-millis: 60000000
  routes:
    blog-api: #服务端
      path: /server/** #配置请求URL的请求规则
      serviceId: blog-server #指定Eureka注册中心中的服务id
      strip-prefix: true #所有的/server的请求都进行转发
      sentiviteHeaders:
      customSensitiveHeaders: true #让zuul网关处理cookie和重定向